### ISSUE TITLE
char_lookup failing on zKill keys

### ISSUE THREAD

**Issue by evidex** [shibdib/Firetail#134]
```requested character info for the user Pech Tor
 [15/06/2018 08:34:40] ERROR events on_command_error 100: CommandInvokeError
 Traceback (most recent call last):
   File "/firetail/firetail/extensions/char_lookup/char_lookup.py", line 75, in _char
     danger_ratio = zkill_stats['dangerRatio']
 KeyError: 'dangerRatio'

 During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "/usr/local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 60, in wrapped
     ret = await coro(*args, **kwargs)
   File "/firetail/firetail/extensions/char_lookup/char_lookup.py", line 165, in _char
     await ctx.message.delete()
   File "/usr/local/lib/python3.6/site-packages/discord/message.py", line 545, in delete
     await self._state.http.delete_message(self.channel.id, self.id)
   File "/usr/local/lib/python3.6/site-packages/discord/http.py", line 210, in request
     raise Forbidden(r, data)
 discord.errors.Forbidden: FORBIDDEN (status code: 403): Missing Permissions```

`char_lookup` extension needs to guard more against zKill returning out of spec results. Command also seems to take quite long to process, and occasionally produces double output. I'll look into submitting a PR to correct this.

**Comment by shibdib** [comment]
char lookup is slow, I need to debug it a bit and figure out where the slowdown is occuring.
